### ISSUE TITLE
Hash of java.rmi differs from expected hash

### ISSUE THREAD

**Issue by tresf** [adoptium/adoptium-support#557]
### Please provide a brief summary of the bug

Builds on GitHub Actions using GitHub's Temurin 11.0.16+8 against Temurin 11.0.12+7 are failing.

### Please provide steps to reproduce where possible

I haven't yet reproduced this locally, but at this point all GitHub builds using `jlink` against the above combinations of Java 11 seem to be affected (MacOS, Linux, Linux targeting Windows)

* GitHub uses `JAVA_HOME`: `/opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/11.0.16-8/x64`
* Project uses Temurin URL: `https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.12+7/OpenJDK11U-jdk_x64_linux_hotspot_11.0.12_7.tar.gz`

### Expected Results

jlink succeeds

### Actual Results

jlink fails

### What Java Version are you using?

JAVA_HOME: /usr/lib/jvm/temurin-11-jdk-amd64

### What is your operating system and platform?

https://github.com/qzind/tray/runs/7662042575?check_suite_focus=true

```yaml
Run actions/setup-java@v2
  with:
    java-version: 11
    distribution: temurin
    java-package: jdk
    architecture: x64
    check-latest: false
    server-id: github
    server-username: GITHUB_ACTOR
    server-password: GITHUB_TOKEN
    overwrite-settings: true
    job-status: success
```

### How did you install Java?

GitHub actions/setup-java@v2

### Did it work before?

Worked with `11.0.15+10`

### Relevant log output

```shell
[java] [DEBUG] 2022-08-03T22:30:24,187 @ qz.utils.ShellUtilities:-1
     [java] 	Executing: [/usr/lib/jvm/temurin-11-jdk-amd64/bin/jlink, --strip-debug, --compress=2, --no-header-files, --no-man-pages, --exclude-files=glob:**/legal/**, --module-path, /home/runner/work/tray/tray/out/jlink/jdk-adoptopenjdk-x64-linux-11.0.12_7/jdk-11.0.12+7/jmods, --add-modules, java.base,java.compiler,java.datatransfer,java.desktop,java.logging,java.management,java.naming,java.net.http,java.prefs,java.rmi,java.scripting,java.security.jgss,java.sql,java.xml,jdk.jfr,jdk.jsobject,jdk.unsupported,jdk.unsupported.desktop,jdk.xml.dom,jdk.zipfs,jdk.crypto.ec, --output, /home/runner/work/tray/tray/out/dist/runtime]
     [java] Error: Hash of java.rmi (f9e89c6c0897e9f27f45f1299ad648dc5a4484c8a197ba19beb2f07900ff3f91) differs to expected hash (fd9918170a44656670ff2dcc5affa75e6a42f1e521c8c62145d27a4189108226) recorded in java.base
Error: ava] [ERROR] 2022-08-03T22:30:24,761 @ qz.utils.ArgParser:-1
     [java] 	Build step JLINK failed
     [java] java.io.IOException: An error occurred deploying the jre.  Please check the logs for details.
```
